/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

void on_wheel_scroll(int);

void on_wheel_scroll(int delta __attribute__((unused))) {
    pitviper_host_scroll(delta);
}

